services:
  # default mcp servers

  time:
    command: uvx mcp-server-time --local-timezone=America/New_York

  fetch:
    command: uvx mcp-server-fetch

  # programming

  github:
    command: npx -y @modelcontextprotocol/server-github
    environment:
      GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN}
    labels:
      mcp.profile: programming

  aws-docs:
    command: uvx awslabs.aws-documentation-mcp-server@latest
    environment:
      FASTMCP_LOG_LEVEL: "${FASTMCP_LOG_LEVEL}"
    labels:
      mcp.profile: programming

  postgres:
    command: npx -y @modelcontextprotocol/server-postgres postgresql://localhost/mydb
    labels:
      mcp.profile: programming, database

  # Container based MCP servers

  github-docker:
    image: ghcr.io/github/github-mcp-server
    environment:
      GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN}
    labels:
      mcp.profile: programming, docker

  brave:
    image: mcp/brave-search
    environment:
      BRAVE_API_KEY: ${BRAVE_API_KEY}
    labels:
      mcp.profile: programming, research

  # Example with volume mounts
  filesystem:
    image: mcp/filesystem
    volumes:
      - ${HOME}/projects:/workspace:ro
      - /tmp:/tmp
    labels:
      mcp.profile: programming
